"use client";

import { Gauge } from "lucide-react";

import { AIConfidencePanel } from "@/components/panels/AIConfidencePanel";
import { ExplanationPanel } from "@/components/panels/ExplanationPanel";
import { PrimaryVitalsPanel } from "@/components/panels/PrimaryVitalsPanel";
import { TrendPanel } from "@/components/panels/TrendPanel";
import { useDatasetReplayMode } from "@/lib/useDataSourceMode";

/**
 * Stage 8 §13 — `/ai-insights` answers one question: *what AI-derived
 * information is, and is not, available for the current source?*
 *
 * The previous page mounted an "AI Confidence" gauge, a "Confidence History"
 * 0–100% trend chart, and two panels titled "Why this confidence score?" /
 * "Why this fatigue estimate?" unconditionally — including during recorded
 * replay, where none of those quantities exist at all. The panels themselves
 * degraded honestly (they rendered "Unavailable"), but the surrounding
 * titles still *asked about a score that was not there*, and the trend chart
 * still drew an empty 0–100% confidence axis. §13 forbids both.
 *
 * The route is now explicitly source-aware and separates the four categories
 * §13 requires: current model output, current availability, synthetic
 * diagnostic score, and offline research explanation.
 */
export function AIInsightsClient() {
  const isReplay = useDatasetReplayMode();

  return (
    <div className="flex flex-col gap-7">
      <header className="flex flex-col gap-2">
        <h1 className="text-2xl font-semibold leading-tight tracking-[-0.02em] text-ink-primary sm:text-[28px]">AI Insights</h1>
        <p className="max-w-3xl text-sm leading-relaxed text-ink-secondary">
          What AI-derived information this demonstrator can and cannot report for the source that is currently selected. Every
          value below is labelled with the source it came from.
        </p>
        <p
          className={
            isReplay
              ? "max-w-3xl rounded-[8px] border border-jury-border-subtle bg-surface-1 px-3.5 py-2.5 text-sm leading-relaxed text-ink-secondary"
              : "max-w-3xl rounded-[8px] border border-experimental/30 bg-experimental-soft px-3.5 py-2.5 text-sm leading-relaxed text-ink-secondary"
          }
        >
          {isReplay ? (
            <>
              <span className="font-semibold text-ink-primary">Recorded replay (PPG-DaLiA).</span> The demonstrated model
              estimates heart rate from PPG + IMU only. It emits no predictive confidence, no uncertainty, and no fatigue
              estimate, so those surfaces below report unavailable rather than a number.
            </>
          ) : (
            <>
              <span className="font-semibold text-experimental">Synthetic demonstrator.</span> The confidence and fatigue
              values below are generated by the synthetic data engine to exercise the interface. They are{" "}
              <span className="font-semibold">not</span> a model output, not a measurement, and carry no scientific meaning.
            </>
          )}
        </p>
      </header>

      <section aria-labelledby="ai-current-output" className="flex flex-col gap-3">
        <h2 id="ai-current-output" className="text-xl font-semibold leading-tight text-ink-primary">
          Current source output
        </h2>
        <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
          <PrimaryVitalsPanel />
          <AIConfidencePanel />
        </div>
      </section>

      {/* A confidence history chart is mounted ONLY when a confidence series
          can genuinely exist. In replay the route states the absence in words
          instead of drawing an empty 0–100% axis (§13). */}
      <section aria-labelledby="ai-confidence-history" className="flex flex-col gap-3">
        <h2 id="ai-confidence-history" className="text-xl font-semibold leading-tight text-ink-primary">
          {isReplay ? "Confidence history — unavailable for this source" : "Synthetic confidence history"}
        </h2>
        {isReplay ? (
          <p className="max-w-3xl rounded-[8px] border border-jury-border-subtle bg-surface-1 px-3.5 py-3 text-sm leading-relaxed text-ink-secondary">
            No confidence series is plotted because the replay heart-rate model produces no confidence value to plot. A chart
            here would require the authoritative model contract to emit a per-frame confidence or uncertainty output, which it
            does not.
          </p>
        ) : (
          <TrendPanel
            title="Synthetic confidence history"
            subtitle="Synthetic demo engine output — not a model confidence"
            icon={<Gauge size={16} />}
            color="#C79A5B"
            unit="%"
            domain={[0, 100]}
            metric="ai_confidence"
          />
        )}
      </section>

      <section aria-labelledby="ai-explanations" className="flex flex-col gap-3">
        <h2 id="ai-explanations" className="text-xl font-semibold leading-tight text-ink-primary">
          {isReplay ? "Feature attribution — unavailable for this source" : "Synthetic feature attribution"}
        </h2>
        <p className="max-w-3xl text-sm leading-relaxed text-ink-secondary">
          {isReplay
            ? "SHAP attribution is not computed for the integrated PPG + IMU heart-rate model and is not validated for it. The panels below state that explicitly rather than attributing a score that does not exist."
            : "SHAP attribution over the synthetic engine's own inputs. This explains the synthetic diagnostic score, not a validated physiological model."}
        </p>
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          <ExplanationPanel
            target="ai_confidence"
            title={isReplay ? "Confidence attribution" : "Why this synthetic confidence score?"}
            subtitle={isReplay ? "No current confidence score for this source" : "SHAP over synthetic sensor signal quality"}
          />
          <ExplanationPanel
            target="fatigue_risk"
            title={isReplay ? "Fatigue attribution" : "Why this synthetic fatigue estimate?"}
            subtitle={isReplay ? "No current fatigue estimate for this source" : "SHAP over synthetic HRV, EEG & mission stress"}
          />
        </div>
      </section>
    </div>
  );
}
